version: "3.7"
services:

    nginx:
        build: requirements/nginx
        ports:
            - '443:443'
        container_name: nginx
        volumes:
            - "/home/tchappui/data/wordpress:/var/www/html"
        env_file:
            - .env
        depends_on:
            - wordpress
        networks:
            - inception
        restart: always

    mysql:
      # tty: true
        build: requirements/mariadb
        ports:
            - '3306:3306'
        container_name: mariadb
        volumes:
            - "/home/tchappui/data/db-data:/var/lib/mysql"
        env_file:
          #- DATABASE_NAME=mariaDB
            - .env
        networks:
            - inception
        restart: always

    wordpress:
        build: requirements/wordpress
        ports:
        - '9000:9000'
        container_name: wordpress
        volumes:
            - "/home/tchappui/data/wordpress:/var/www/html"
        env_file:
           - .env
        depends_on:
            - mysql
        networks:
            - inception
        restart: always

networks:
  inception:
    driver: bridge 
volumes:
    wordpress:
    db-data:
