FROM alpine:3.16

RUN apk update && apk add mariadb mariadb-client
RUN mkdir /var/run/mysqld; \
	chmod 777 /var/run/mysqld; \
	sed -i "s|skip-networking|skip-networking=0|g" \
      /etc/my.cnf.d/mariadb-server.cnf

COPY ./conf/mariadb.cnf /etc/my.cnf.d/
COPY ./tools/maria.sh .
RUN chmod +x "./maria.sh"
CMD ["./maria.sh"]
