FROM alpine:3.15

RUN apk update && apk upgrade
RUN apk add mariadb mariadb-client
RUN chmod 755 /var/lib/mysql
RUN rm /etc/my.cnf.d/mariadb-server.cnf /etc/my.cnf

COPY ./conf/mariadb.cnf /etc/my.cnf.d/my.cnf

CMD ["/bin/sh"]