FROM alpine:3.16

RUN apk update && apk upgrade
RUN apk add mariadb mariadb-client
RUN chmod 777 /var/lib/mysql
RUN mkdir /var/run/mysqld; \
	chmod 777 /var/run/mysqld
RUN mysql_install_db --user=mysql --datadir=/var/lib/mysql

COPY ./conf/mariadb.cnf /etc/my.cnf.d/
COPY ./tools/maria.sh .
RUN chmod +x "./maria.sh"

CMD ["./maria.sh"]
