FROM alpine:3.15

RUN apk update && apk upgrade && apk add php7 php7-fpm php7-mysqli 
RUN sed -i "s|listen = 127.0.0.1:9000|listen = 0.0.0.0:9000|g" /etc/php7/php-fpm.d/www.conf
COPY ./conf/wp-config.php .
COPY ./tools/wordpress.sh .

CMD ["sh", "wordpress.sh"]
