FROM alpine:3.15

RUN apk update && apk upgrade && apk add php7 php7-fpm php7-mysqli
RUN mkdir -p /var/www/html/ && cd /var/www/html && wget http://wordpress.org/latest.tar.gz && tar -xzvf latest.tar.gz && rm latest.tar.gz
#RUN chmod 777 /var/www/html && mv 

COPY ./conf/wp-config.php /var/www/wordpress/wp-config.php

CMD ["/usr/sbin/php-fpm7", "-F"]
