FROM alpine:3.16

RUN apk update && apk upgrade
RUN apk add nginx
RUN apk add openssl
RUN openssl req -new -newkey rsa:2048 -batch -nodes -keyout /etc/ssl/tchappui.key -out /etc/ssl/tchappui.csr -subj "/C=EU/ST=SUISSE/L=Lehi/O=Your"

#RUN chmod 777 -R etc/ssl
COPY ./conf/nginx.conf /etc/nginx/http.d/

CMD ["nginx", "-g", "daemon off;"]
